// 「工具失败之后」：重试、退避、幂等。
// 三种失败里第三种最危险：你不知道它到底做没做。

import type { L } from "@/lib/i18n";
import type { Block, LessonMeta } from "@/lib/lesson";

export type Failure = {
  id: "errored" | "timedout" | "unknown";
  name: L;
  saw: L;
  // 你知道那个动作有没有真的发生吗
  knows: L;
  certain: boolean;
  safeToRetry: L;
  tone: "ok" | "warn" | "bad";
};

export const failures: Failure[] = [
  {
    id: "errored",
    name: { zh: "报错了", en: "It errored" },
    saw: {
      zh: "exit 1，stderr 里写着 connection refused。",
      en: "exit 1, and stderr says connection refused.",
    },
    knows: {
      zh: "知道。请求根本没被受理，那一侧什么都没发生。",
      en: "You do. The request was never accepted; nothing happened on the far side.",
    },
    certain: true,
    safeToRetry: {
      zh: "可以直接重试。这是三种里最省心的一种——虽然它看起来最吓人。",
      en: "Retry it. This is the easiest of the three to handle, and it is the one that looks the most alarming.",
    },
    tone: "ok",
  },
  {
    id: "timedout",
    name: { zh: "超时了", en: "It timed out" },
    saw: {
      zh: "等了 30 秒，你的代码放弃等待。",
      en: "Thirty seconds passed and your code stopped waiting.",
    },
    knows: {
      zh: "不知道。超时说明的是「你没等到回音」，不是「对方没做」。请求可能已经到了、已经执行完了，只是回程的包丢了。",
      en: "You do not. A timeout says you stopped hearing, not that nothing happened. The request may have arrived, run to completion, and lost only the reply.",
    },
    certain: false,
    safeToRetry: {
      zh: "取决于这个工具本身。安全就重试，不安全就不能——这正是下一节要解决的问题。",
      en: "It depends on the tool. Safe to repeat means retry; not safe means you cannot, which is what the next section is about.",
    },
    tone: "warn",
  },
  {
    id: "unknown",
    name: { zh: "你这边先断了", en: "Your side died first" },
    saw: {
      zh: "进程被杀 / 容器重启 / 网络断了。请求发出去了，之后的事你一无所知。",
      en: "The process was killed, the container restarted, the link dropped. The request went out and you know nothing after that.",
    },
    knows: {
      zh: "不知道，而且比超时更彻底——你连有没有发出去都不一定确定。",
      en: "You do not, and less than with a timeout: you may not even be certain it left.",
    },
    certain: false,
    safeToRetry: {
      zh: "同上，而且这一种最容易被忽略，因为它经常连一条日志都没有留下。",
      en: "Same answer, and this is the one most often overlooked, because it frequently leaves no log line at all.",
    },
    tone: "bad",
  },
];

export type Tool = {
  name: string;
  what: L;
  idempotent: boolean;
  twice: L;
  fix?: L;
};

export const tools: Tool[] = [
  {
    name: "search_files(query)",
    what: { zh: "在项目里搜一段文字", en: "search the project for a string" },
    idempotent: true,
    twice: {
      zh: "跑两次和跑一次的结果一样。重试不需要任何额外考虑。",
      en: "Running it twice gives what running it once gave. Retrying needs no further thought.",
    },
  },
  {
    name: "read_file(path)",
    what: { zh: "读一个文件", en: "read a file" },
    idempotent: true,
    twice: {
      zh: "同上。读取天然可以重复——这也是[[stop:/permission]]说读和写不一样的另一个理由。",
      en: "The same. Reads repeat safely, which is another reason [[stop:/permission]] treats them differently from writes.",
    },
  },
  {
    name: "charge_card(amount)",
    what: { zh: "扣一笔钱", en: "charge a card" },
    idempotent: false,
    twice: {
      zh: "跑两次就扣两笔。超时之后如果盲目重试，用户被扣了两次，而你的日志里只有一次成功。",
      en: "Twice means charged twice. Retry blindly after a timeout and the customer is charged twice while your log shows one success.",
    },
    fix: {
      zh:
        "加一个幂等键：charge_card(amount, key: \"order-8241\")。" +
        "服务端记住这个 key 处理过了，第二次带着同一个 key 来，它返回第一次的结果，不再扣钱。" +
        "key 要由发起方生成、跟这次业务绑定，而且重试时必须原样用同一个。",
      en:
        "Give it an idempotency key: charge_card(amount, key: \"order-8241\"). The far side remembers it " +
        "handled that key, so a second call carrying the same one returns the first result and charges " +
        "nothing. The key is generated by the caller, tied to the piece of work, and reused unchanged on " +
        "every retry.",
    },
  },
  {
    name: "send_email(to, body)",
    what: { zh: "发一封邮件", en: "send an email" },
    idempotent: false,
    twice: {
      zh: "收件人收到两封。比扣两次钱轻，但同样是不可撤销的。",
      en: "The recipient gets two. Lighter than a double charge, and just as impossible to take back.",
    },
    fix: {
      zh: "同样用一个键去重，或者把「发送」拆成两步：先写进待发队列（可重复），再由一个单独的、只跑一次的流程发出去。",
      en: "The same key, or split sending into two steps: write to an outbox, which repeats safely, and let a separate process that runs once do the sending.",
    },
  },
];

// 指数退避：第 n 次重试等多久。加一点抖动，避免所有客户端同时回来。
export const BASE_MS = 500;
export const MAX_ATTEMPTS = 5;

export function backoffMs(attempt: number): number {
  return BASE_MS * Math.pow(2, attempt - 1);
}

export function totalWaitMs(attempts: number): number {
  let total = 0;
  for (let i = 1; i < attempts; i++) total += backoffMs(i);
  return total;
}

// ---------------------------------------------------------------- 文案

export const meta: LessonMeta = {
  title: { zh: "工具失败之后", en: "When a tool fails" },
  subtitle: {
    zh: "一次调用有三种失败方式，其中一种你不知道它到底做没做——而重试会把那件事再做一遍。",
    en: "A call can fail in three ways, and in one of them you do not know whether the work happened — which is the one a retry does twice.",
  },
  takeaway: {
    zh:
      "**要么给 agent 一批重复调用也安全的工具，要么给它们一个键，让第二次调用什么也不做。**" +
      "重试和退避是简单的部分；难的部分是先分清哪些动作重复一遍不会出事。",
    en:
      "**Either give an agent tools that are safe to call twice, or give them a key that makes the second " +
      "call do nothing.** Retries and backoff are the easy part; the hard part is knowing which actions can " +
      "be repeated without consequence.",
  },
};

export const blocks: Block[] = [
  {
    title: { zh: "三种失败，不是一种", en: "Three failures, not one" },
    paras: [
      {
        zh:
          "[[stop:/loop]]有一次运行是工具执行失败，那一站关心的是「把什么写进[[array:数组]]」。" +
          "这一站关心的是另一半：**你的代码接下来该不该再试一次。**" +
          "答案取决于它是怎么失败的，而失败有三种，不是一种。",
        en:
          "One of the runs at [[stop:/loop]] was a tool failing, and that stop asked what to put in the " +
          "[[array:array]]. This one asks the other half: **should your code try again?** The answer depends " +
          "on how it failed, and there are three ways, not one.",
      },
      {
        zh:
          "把上面三种各点开一次，看中间那一栏——「你知道那个动作有没有发生吗」。" +
          "报错的那一种你知道：请求没被受理，对面什么都没做，重试是安全的。" +
          "后两种你不知道。**超时说明的是你没等到回音，不是对方没做。**" +
          "请求可能已经送到、已经执行完，只是回程丢了；" +
          "而你这边先崩了的那一种更糟，你连它有没有发出去都不确定。",
        en:
          "Open each of the three above and read the middle column — do you know whether the work happened? " +
          "With an error you do: the request was refused, nothing ran, and retrying is safe. With the other " +
          "two you do not. **A timeout says you stopped hearing, not that nothing happened.** The request may " +
          "have arrived and completed with only the reply lost. And the one where your own side died is worse " +
          "still: you may not even be sure it left.",
      },
      {
        zh:
          "这三种在日志里长得差不多，都是「这次调用没成功」，" +
          "所以最常见的处理方式是一视同仁地重试一次。" +
          "对前两种里的第一种，这是对的；对后两种，这可能意味着那件事被做了两遍。",
        en:
          "All three look alike in a log — this call did not succeed — so the common treatment is to retry all " +
          "of them once. For the first that is right. For the other two it can mean the work was done twice.",
      },
    ],
    faq: {
      q: {
        zh: "把超时时间调长，是不是就没这个问题了？",
        en: "Does a longer timeout make this go away?",
      },
      a: {
        zh:
          "不会，只是把它推远。任何有限的等待时间都存在「等到超时那一刻，对面其实刚做完」这种可能，" +
          "而且等得越久，用户和上游的容忍度就越低——你只是把不确定性从 30 秒挪到了 5 分钟。" +
          "真正解决它的办法不在等待这一侧，在动作那一侧：让重复调用不会造成第二次后果。",
        en:
          "No, it moves it further away. Any finite wait has a moment where you give up just as the far side " +
          "finishes, and the longer you wait the less patience the user and everything upstream has. You have " +
          "moved the uncertainty from thirty seconds to five minutes. The fix is not on the waiting side but " +
          "on the action side: make a repeated call unable to have a second effect.",
      },
    },
  },
  {
    title: { zh: "重试要有次数，也要有间隔", en: "Retries need a limit and a gap" },
    paras: [
      {
        zh:
          "重试本身有两条几乎不用讨论的规矩。" +
          "第一条：**次数要有上限。**没有上限的重试和[[stop:/loop]]那个停不下来的循环是同一种东西，" +
          "只是它连模型的钱都不花，直接把对面打垮。" +
          "第二条：**每次之间要等，而且越等越久**（指数退避）。" +
          "上面那张表就是 500 毫秒起步、每次翻倍的样子。",
        en:
          "Two rules about retries barely need arguing. First, **cap the number of attempts.** Uncapped " +
          "retries are the same object as the loop that would not stop at [[stop:/loop]], except that this one does " +
          "not even spend model tokens — it just flattens whatever it is calling. Second, **wait between " +
          "them, and wait longer each time** (exponential backoff). The table above is 500 ms doubling.",
      },
      {
        zh:
          "退避的理由值得说清楚：失败常常是因为对面过载，而立刻重试会加重过载。" +
          "如果同时有一百个客户端都在立刻重试，你制造的不是恢复，是第二波冲击。" +
          "所以实践中还会给等待时间加一点随机抖动，让大家不要在同一毫秒一起回来。",
        en:
          "The reason for backing off is worth stating: failures are often caused by the far side being " +
          "overloaded, and an immediate retry adds to the overload. With a hundred clients all retrying " +
          "immediately, what you have built is not a recovery but a second wave. In practice the wait also " +
          "gets a little random jitter, so that everyone does not come back in the same millisecond.",
      },
    ],
  },
  {
    title: { zh: "真正的解法：让第二次调用什么也不做", en: "The real fix: make the second call do nothing" },
    paras: [
      {
        zh:
          "上面第二张表把四个工具排在一起。前两个重复调用完全无害：" +
          "搜两次和搜一次结果一样，读两次和读一次结果一样。" +
          "这类工具叫**幂等**（idempotent）——做一次和做很多次，效果相同。" +
          "对它们，重试不需要任何额外的设计。",
        en:
          "The second table above puts four tools side by side. The first two repeat harmlessly: searching " +
          "twice gives what searching once gave, and so does reading. Tools like that are called " +
          "**idempotent** — doing it many times has the same effect as doing it once. For them, retrying " +
          "needs no design at all.",
      },
      {
        zh:
          "后两个不是。扣款调两次就扣两笔，发信调两次就发两封。" +
          "在这两个上面，一次超时之后的盲目重试就是一次真实损失，" +
          "而且损失发生在你的日志显示「一次成功」的情况下——最难查的那种。",
        en:
          "The last two are not. Charging twice charges twice; sending twice sends twice. On those, a blind " +
          "retry after a timeout is a real loss, and it happens while your log shows a single success, which " +
          "is the hardest kind to find.",
      },
      {
        zh:
          "解法是给这次动作一个**幂等键**：由发起方生成、跟这件事绑定的一个字符串，" +
          "比如 charge_card(amount, key: \"order-8241\")。" +
          "对面记住这个 key 已经处理过，第二次带着同一个 key 来，它返回第一次的结果，不再扣钱。" +
          "关键在于重试时必须用**同一个** key——每次重试新生成一个，等于没做。",
        en:
          "The fix is to give the action an **idempotency key**: a string generated by the caller and tied to " +
          "this piece of work, as in charge_card(amount, key: \"order-8241\"). The far side remembers it has " +
          "handled that key, so a second call carrying the same one returns the first result and charges " +
          "nothing. What matters is that a retry reuses **the same** key — generating a fresh one per attempt " +
          "is the same as having none.",
      },
      {
        zh:
          "把这条放回 agent 的语境里，它就变成一条工具设计的规矩：" +
          "**给 agent 的工具，要么重复调用安全，要么带键。**" +
          "理由在[[stop:/chance]]已经讲过——你没法保证同一个 agent 跑两次会做同样的事，" +
          "也没法保证它不会因为一次超时就把刚才那步再来一遍。" +
          "与其在提示词里叮嘱它「不要重复扣款」（[[stop:/instructions]]说过那有多弱），不如让重复扣款做不到。",
        en:
          "Put that back into the agent setting and it becomes a rule about tool design: **the tools you give " +
          "an agent are either safe to call twice or they carry a key.** The reason is the one from [[stop:/chance]]: " +
          "you cannot guarantee that the same agent run twice does the same thing, and you cannot guarantee " +
          "it will not repeat a step after a timeout. Rather than telling it in the prompt not to " +
          "double-charge — [[stop:/instructions]] covered how weak that is — make double-charging impossible.",
      },
    ],
    faq: {
      q: {
        zh: "让模型自己判断该不该重试，行不行？",
        en: "Can the model decide whether to retry?",
      },
      a: {
        zh:
          "可以让它参与，但不能只靠它。模型能看到的只有你写进 tool_result 的那段文字（[[stop:/loop]]），" +
          "所以「这次到底做没做」这个信息，得先由你的代码放进去，它才可能判断对。" +
          "而且就算它判断对了，它也只是倾向正确——[[stop:/chance]]那条依然成立。" +
          "稳妥的分工是：安全性由工具的结构保证，模型只负责在安全的选项里挑一个。",
        en:
          "It can take part, and it cannot be the only thing deciding. The model sees only what you wrote " +
          "into the tool_result ([[stop:/loop]]), so whether the work happened has to be put there by your code " +
          "before it can judge correctly. And even when it judges correctly it is only likely to — [[stop:/chance]] " +
          "still applies. The workable split is that safety comes from the structure of the tool, and the " +
          "model chooses among options that are already safe.",
      },
    },
  },
];

export const bench = {
  title: { zh: "三种失败，一个问题", en: "Three failures, one question" },
  note: { zh: "点开看中间那一栏", en: "read the middle column" },
  chooseLabel: { zh: "这次调用是怎么失败的", en: "How did the call fail" },
  sawWord: { zh: "你这边看到的", en: "What you saw" },
  knowsWord: { zh: "那个动作发生了吗", en: "Did the work happen" },
  retryWord: { zh: "能不能重试", en: "Can you retry" },
  certainYes: { zh: "确定", en: "certain" },
  certainNo: { zh: "不确定", en: "not certain" },
  toolsTitle: { zh: "调两次会怎样", en: "What happens if you call it twice" },
  toolCol: { zh: "工具", en: "Tool" },
  twiceCol: { zh: "调两次", en: "Called twice" },
  safeWord: { zh: "重复安全", en: "safe to repeat" },
  unsafeWord: { zh: "重复有害", en: "not safe" },
  fixWord: { zh: "怎么修", en: "The fix" },
  backoffTitle: { zh: "退避", en: "Backing off" },
  attemptCol: { zh: "第几次重试", en: "Attempt" },
  waitCol: { zh: "等多久", en: "Wait" },
  totalWord: { zh: "累计等待", en: "total wait" },
};
